application:
  keys:
    parameter: "application.parameter."
    element:  "application.element."
  expirationMs:
    parameter: 180000
    element: 300000
redis:
  host: localhost
  port: 6379
  timeout: 1000ms
  socket.timeout: 1000ms